#!/bin/bash

set -eu

REPO=$(git config --get remote.origin.url | sed 's/\.git$//g')
BRANCH=$(git rev-parse --abbrev-ref HEAD)
WORKDIR=$(git rev-parse --show-prefix | sed 's%\/$%%g')

if ! echo $REPO | grep -E -q "backlog.(jp|com)(:|/)" ; then
  exit 1
fi

if echo $REPO | grep -q "^https://" ; then
  # HTTP
  BASEURL=$(echo $REPO | sed 's/\.git\./\./g')
else
  # SSH
  REPO2=$(echo $REPO | sed 's%^ssh://%%g' | sed 's%:/%/%g')
  DOMAIN=$(echo $REPO2 | awk -F'[@/]' '{print $2}' | sed 's/\.git\./\./g')
  SUBDIR=$(echo $REPO2 | awk -F'[@/]' '{print $3"/"$4}')
  BASEURL=https://$DOMAIN/git/$SUBDIR
fi

URL=$BASEURL/tree/$BRANCH/$WORKDIR

echo $URL
open $URL
